version: '3.9'

services:

  # Application layer ---------------------------------------------------------------

  # Data layer ----------------------------------------------------------------------

  db:
    image: postgres:11
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    # only expose port if you need DB access from outside of docker
    ports:
      - 5432:5432

volumes:
  postgres-data:
    driver: local
